name: xcube-sh
channels:
  - conda-forge
  - defaults
dependencies:

  # Required
  - xcube >=0.6
  - oauthlib >=3.0
  - pip >=19.1
  - psycopg2 >= 2.8.4

  # Inspection
  - jupyterlab
  - matplotlib

  - pip:
    # Required
    - requests_oauthlib
